### ISSUE TITLE
How to call software_reset() function Adafruit_Python_PCA9685 ?

### ISSUE THREAD

**Issue by AyoubELKatibi** [adafruit/Adafruit_Python_PCA9685#12]
How to call software_reset() function Adafruit_Python_PCA9685 ?

**Comment by knabbers** [comment]
I don't think you can! It should be inside the class, as it refers to self.

**Comment by caternuson** [comment]
Hello. This library is being deprecated. Please use the new replacement library here:
https://github.com/adafruit/Adafruit_CircuitPython_PCA9685
Setup instructions here:
https://learn.adafruit.com/16-channel-pwm-servo-driver/python-circuitpython

If the issue still exists, please open a new issue in the new library repo:
https://github.com/adafruit/Adafruit_CircuitPython_PCA9685/issues
