### ISSUE TITLE
setuptools-3.5.1.zip download not working

### ISSUE THREAD

**Issue by cimbusch** [adafruit/Adafruit_Python_PCA9685#15]
Install procedure via download of https://pypi.python.org/packages/source/s/setuptools/setuptools-3.5.1.zip does not work anymore. It's not hosted there anymore.

pi@raspberrypi:~/Adafruit_Python_PCA9685 $ sudo python setup.py install
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-3.5.1.zip
Extracting in /tmp/tmpYeIU5n
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
...
zipfile.BadZipfile: File is not a zip file

**Comment by ladyada** [comment]
this library is beign deprecated, so it wont be fixed or maintained anymore - please use
https://learn.adafruit.com/16-channel-pwm-servo-driver/python-circuitpython
our new python3 library set :)
