### ISSUE TITLE
No full on & full off mode?

### ISSUE THREAD

**Issue by chupocro** [adafruit/Adafruit_Python_PCA9685#18]
One of often used features of PCA9685 IC is **full on** and **full off** mode of its outputs (bit 4 of LEDn_ON_H and bit 4 of LEDn_OFF_H registers). The library should allow using all features of the IC.

**Comment by caternuson** [comment]
Hello. This library is being deprecated. Please use the new replacement library here:
https://github.com/adafruit/Adafruit_CircuitPython_PCA9685
Setup instructions here:
https://learn.adafruit.com/16-channel-pwm-servo-driver/python-circuitpython

If the issue still exists, please open a new issue in the new library repo:
https://github.com/adafruit/Adafruit_CircuitPython_PCA9685/issues
