### ISSUE TITLE
Relies on deprecated Adafruit_GPIO.Platform for RPI4 support

### ISSUE THREAD

**Issue by Robert-L-Turner** [adafruit/Adafruit_Python_PCA9685#19]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  

Hardware	: BCM2711
Revision	: d03114
Serial		: 1000000098966e85
Model		: Raspberry Pi 4 Model B Rev 1.4

'Linux-5.10.52-1-ARCH-armv7l-with-glibc2.32'

- Python version (run `python -version` or `python3 -version`):  

Python 3.9.6

- Error message you are receiving, including any Python exception traces:  
     ```
pwm = Adafruit_PCA9685.PCA9685()
     File "/usr/lib/python3.9/site-packages/Adafruit_PCA9685/PCA9685.py", line 74, in __init__
       self._device = i2c.get_i2c_device(address, **kwargs)
     File "/usr/lib/python3.9/site-packages/Adafruit_GPIO/I2C.py", line 63, in get_i2c_device
       busnum = get_default_bus()
     File "/usr/lib/python3.9/site-packages/Adafruit_GPIO/I2C.py", line 55, in get_default_bus
       raise RuntimeError('Could not determine default I2C bus for platform.')
```

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): 

Create a pwm PCA9685 device on a Raspberry Pi 4.

PCA9685 -> gets the i2c device 
I2C.py -> gets_default_bus device (if not specified) via Platform.py
Platform.py -> case matches /proc/cpuinfo to RPI platforms but does not include BCM2711 as a match case

Adafruit_GPIO is deprecated so I presume you are no longer accepting pull requests to update the platform identification to support the RPI4.  Will the PCA9685 library be rewritten to leverage the replacement of the GPIO library?

**Comment by ladyada** [comment]
yep please use
https://github.com/adafruit/Adafruit_CircuitPython_PCA9685
:)

**Comment by Robert-L-Turner** [comment]
Amazing to get a reply from someone doing so much just 7 minutes after I open the issue!  

I note the new code base doesn't seem to have the same platform detection functionality and instead the i2c bus is a required argument.  Was this a conscious decision or a potential pull request to implement?

Apologies if its an obvious question but I have been hunting for a first PR opportunity.

**Comment by ladyada** [comment]
the other library fits our standard circuitpython library api - we wouldn't change it since many platforms have multilple i2c ports

**Comment by Robert-L-Turner** [comment]
Thank you, it was not so much to force the selection of the i2c port, rather it is to support backwards compatibility with existing code bases:

```
def get_i2c_device(address, busnum=None, i2c_interface=None, **kwargs):
    """Return an I2C device for the specified address and on the specified bus.
    If busnum isn't specified, the default I2C bus for the platform will attempt
    to be detected.
    """
    if busnum is None:
        busnum = get_default_bus()
    return Device(address, busnum, i2c_interface, **kwargs)
```
The get_default_bus allows the code to not be platform specific on the bus selection...I think that is pretty beginner friendly.

If I want to move to the new API, it breaks the broader code base as the method to set PWM frequency is different in addition to the bus selection being hard coded.  It was easier to just insert the additional case statement into the deprecated code base for the moment.
