### ISSUE TITLE
Could not determine default I2C bus for platform

### ISSUE THREAD

**Issue by cheeryoung79** [adafruit/Adafruit_Python_PCA9685#20]
Rappy Pi 3B+
python simpletest.py err
![7}XP{HBJZ{_K_{P47`K1IUQ](https://user-images.githubusercontent.com/18297295/138818541-46a4c105-7da0-4964-8982-7d5c56b47ae1.jpg)

**Comment by caternuson** [comment]
Hello. This library is being deprecated. Please use the new replacement library here:
https://github.com/adafruit/Adafruit_CircuitPython_PCA9685
Setup instructions here:
https://learn.adafruit.com/16-channel-pwm-servo-driver/python-circuitpython

If the issue still exists, please open a new issue in the new library repo:
https://github.com/adafruit/Adafruit_CircuitPython_PCA9685/issues
