### ISSUE TITLE
NVIDIA Jetson TK1 support

### ISSUE THREAD

**Issue by varundevsukhil** [adafruit/Adafruit_Python_PCA9685#6]
Hello,

Can you please add support for the TK1/TX1/TX2 platforms?

Thanks,

**Comment by sagnibak** [comment]
@varundevsukhil have you tried to install it on one of the Jetson boards? Does it not work on them?

**Comment by varundevsukhil** [comment]
@sagnibak I tried on a TK1 and a TX2, and unfortunately it does not work!

**Comment by ladyada** [comment]
hiya we now have `blinka` support for jetson, please try it
https://learn.adafruit.com/circuitpython-libraries-on-linux-and-the-nvidia-jetson-nano
