### ISSUE TITLE
Why frequency overshoot is not patched in Python version?

### ISSUE THREAD

**Issue by rickyzhang82** [adafruit/Adafruit_Python_PCA9685#7]
First of all, I don't own a scope to verify this.

But by reading the code between Python version and Arduino version, it seems that [frequency overshoot patch](https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library/issues/11) has not applied in Python version library.

**Comment by caternuson** [comment]
Hello. This library is being deprecated. Please use the new replacement library here:
https://github.com/adafruit/Adafruit_CircuitPython_PCA9685
Setup instructions here:
https://learn.adafruit.com/16-channel-pwm-servo-driver/python-circuitpython

If the issue still exists, please open a new issue in the new library repo:
https://github.com/adafruit/Adafruit_CircuitPython_PCA9685/issues
